version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    networks:
      - hadoop-network
    volumes:
      - namenode-data:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
      - "9000:9000"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode
    networks:
      - hadoop-network
    volumes:
      - datanode-data:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    depends_on:
      - namenode

  spark-client:
    image: bitnami/spark:3
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./data:/data
      - ./spark-apps:/apps
    networks:
      - hadoop-network
    depends_on:
      - namenode
      - datanode

volumes:
  namenode-data:
  datanode-data:

networks:
  hadoop-network:
    driver: bridge
