version: '3.8'

services:
  zookeeper1:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper1
    hostname: zookeeper1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    networks:
      - hadoop-network
    volumes:
      - zookeeper1-data:/bitnami/zookeeper
    
  zookeeper2:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper2
    hostname: zookeeper2
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    networks:
      - hadoop-network
    volumes:
      - zookeeper2-data:/bitnami/zookeeper

  zookeeper3:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper3
    hostname: zookeeper3
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    networks:
      - hadoop-network
    volumes:
      - zookeeper3-data:/bitnami/zookeeper

  journalnode1:
    image: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
    container_name: journalnode1
    hostname: journalnode1
    command: ["hdfs", "journalnode"]
    networks:
      - hadoop-network
    volumes:
      - journalnode1-data:/hadoop/dfs/journal
      - ./config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./config/core-site.xml:/etc/hadoop/core-site.xml
    environment:
      - CLUSTER_NAME=test-ha
    ports:
      - "8485:8485"

  journalnode2:
    image: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
    container_name: journalnode2
    hostname: journalnode2
    command: ["hdfs", "journalnode"]
    networks:
      - hadoop-network
    volumes:
      - journalnode2-data:/hadoop/dfs/journal
      - ./config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./config/core-site.xml:/etc/hadoop/core-site.xml
    environment:
      - CLUSTER_NAME=test-ha
    ports:
      - "8486:8485"
    
  journalnode3:
    image: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
    container_name: journalnode3
    hostname: journalnode3
    command: ["hdfs", "journalnode"]
    networks:
      - hadoop-network
    volumes:
      - journalnode3-data:/hadoop/dfs/journal
      - ./config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./config/core-site.xml:/etc/hadoop/core-site.xml
    environment:
      - CLUSTER_NAME=test-ha
    ports:
      - "8487:8485"


  namenode1:
    build: './ha-hadoop-namenode'
    container_name: namenode1
    hostname: namenode1
    networks:
      - hadoop-network
    volumes:
      - ./hdfs-data:/data:rw
      - ./config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./config/core-site.xml:/etc/hadoop/core-site.xml
      - namenode1-data:/hadoop/dfs/name
    ports:
      - "9870:9870"
    environment:
      - CLUSTER_NAME=test-ha
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - journalnode1
      - journalnode2
      - journalnode3

  namenode2:
    build: './ha-hadoop-namenode'
    container_name: namenode2
    hostname: namenode2
    networks:
      - hadoop-network
    volumes:
      - ./config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./config/core-site.xml:/etc/hadoop/core-site.xml
      - namenode2-data:/hadoop/dfs/name
    ports:
      - "9871:9870"
    environment:
      - CLUSTER_NAME=test-ha
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - journalnode1
      - journalnode2
      - journalnode3


  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    hostname: datanode1
    networks:
      - hadoop-network
    volumes:
      - ./config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./config/core-site.xml:/etc/hadoop/core-site.xml
      - datanode1-data:/hadoop/dfs/data
    environment:
      - CLUSTER_NAME=test-ha
      
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - journalnode1
      - journalnode2
      - journalnode3
      - namenode1
      - namenode2

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    hostname: datanode2
    networks:
      - hadoop-network
    volumes:
      - ./config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./config/core-site.xml:/etc/hadoop/core-site.xml
      - datanode2-data:/hadoop/dfs/data
    environment:
      - CLUSTER_NAME=test-ha
      
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - journalnode1
      - journalnode2
      - journalnode3
      - namenode1
      - namenode2

  spark-client:
    image: bitnami/spark:3
    hostname: spark-client
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./spark-apps:/spark-apps
      - ./config/core-site.xml:/opt/bitnami/spark/conf/core-site.xml
      - ./config/hdfs-site.xml:/opt/bitnami/spark/conf/hdfs-site.xml
    networks:
      - hadoop-network
    ports:
      - "4040:4040"
    environment:
      - HADOOP_USER_NAME=root
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - journalnode1
      - journalnode2
      - journalnode3
      - namenode1
      - namenode2
      - datanode1
      - datanode2

networks:
  hadoop-network:

volumes:
  namenode1-data:
  namenode2-data:
  datanode1-data:
  datanode2-data:
  journalnode1-data:
  journalnode2-data:
  journalnode3-data:
  zookeeper1-data:
  zookeeper2-data:
  zookeeper3-data: