version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      hadoop-network:
        aliases:
          - zookeeper

  journalnode:
    build: ./hadoop-docker
    hostname: journalnode
    command: ["hdfs", "journalnode"]
    networks:
      hadoop-network:
        aliases:
          - journalnode
    volumes:
      - ./config:/opt/hadoop/etc/hadoop

  namenode1:
    build: ./hadoop-docker
    hostname: namenode1
    command: ["hdfs", "namenode"]
    networks:
      hadoop-network:
        aliases:
          - namenode1
    volumes:
      - namenode1-data:/hadoop/dfs/name
      - ./config:/opt/hadoop/etc/hadoop
    ports:
      - "9870:9870"
      - "9000:9000"
    depends_on:
      - journalnode
      - zookeeper

  namenode2:
    build: ./hadoop-docker
    hostname: namenode2
    command: ["hdfs", "namenode"]
    networks:
      hadoop-network:
        aliases:
          - namenode2
    volumes:
      - namenode2-data:/hadoop/dfs/name
      - ./config:/opt/hadoop/etc/hadoop
    ports:
      - "9871:9870"
    depends_on:
      - journalnode
      - zookeeper

  datanode:
    build: ./hadoop-docker
    hostname: datanode
    command: ["hdfs", "datanode"]
    networks:
      hadoop-network:
        aliases:
          - datanode
    volumes:
      - datanode-data:/hadoop/dfs/data
      - ./config:/opt/hadoop/etc/hadoop
    depends_on:
      - namenode1
      - namenode2

  spark-client:
    image: bitnami/spark:3
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./data:/data
      - ./spark-apps:/apps
      - ./config/core-site.xml:/opt/bitnami/spark/conf/core-site.xml
      - ./config/hdfs-site.xml:/opt/bitnami/spark/conf/hdfs-site.xml
    networks:
      - hadoop-network
    depends_on:
      - namenode1
      - namenode2
      - datanode

volumes:
  namenode1-data:
  namenode2-data:
  datanode-data:

networks:
  hadoop-network:
    driver: bridge
